config/routes.rb
Interapptive::Application.routes.draw do

  root :to => 'admin::users#index', :constraints => lambda { |request| request.cookies['auth_token'] && request.cookies['is_admin'] }
  root :to => 'storybooks#index', :constraints => lambda { |request| request.cookies['auth_token'] }
  root :to => 'user_sessions#new'

  #get  'users/sign_up'  => 'users#new',             :as => 'sign_up'
  get  'users/sign_in'  => 'user_sessions#new',     :as => 'sign_in'
  post 'users/sign_in'  => 'user_sessions#create',  :as => ''
  match 'users/sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  get  'users/settings'  => 'users#edit'

  resource :user do
    collection { get :show_signed_in_as_user }
  end

  get  'password_reset'      => 'password_resets#new',   :as => :new_password_reset
  get  'password_resets/:id' => 'password_resets#edit',  :as => :edit_password_reset
  put  'password_resets/:id' => 'password_resets#update'
  post 'password_resets'     => 'password_resets#create'

  resource :compiler
  resource :confirmation, only: [:new, :create]
  resource :term,         only: [:new, :create], :path_names => { :new => 'accept' }, :path => 'terms'
  resource :kmetrics,   only: :create

  resources :images
  resources :videos
  resources :sounds
  resources :fonts

  get '/storybooks/main', to: redirect('/assets/init_storybook.js')
  get '/storybooks/res/:name', to: redirect('/assets/res/%{name}.png')
  resources :storybooks do
    resources :scenes do
      collection { put :sort }
    end

    resources :fonts
    resources :images
    resources :videos
    resources :sounds
    resources :assets, only: [:create, :index]

    resource :application_information, only: [:create, :update]
    resource :subscription_publish_information, only: [:update]
    resource :subscription_publish_request, only: [:create]

    get 'simulator/show' => 'simulator#show'
    get 'simulator/main', to: redirect('/assets/simulator.js')
  end

  resources :scenes do
    #resources :actions

    resources :keyframes do
      collection { put :sort }
    end
  end

  resources :keyframes

  resource :zencoder, :controller => :zencoder, :only => :create

  namespace :admin do
    root :to => 'users#index'

    resources :subscription_users do
      collection do
        get 'search'
      end

      member do
        post 'restore'
      end
    end

    resources :users do
      collection do
        get 'search'
      end
      member do
        post 'send_invitation'
        post 'restore'
      end
    end

    resource :subscription_publisher, only: :create

    resources :publish_requests,              only: [:index, :show, :update]
    resources :subscription_publish_requests, only: [:index, :show, :update]
    resources :storybook_assignments,         only: [:edit, :update]
    resources :storybook_archives,            only: [:create]
    resources :auto_alignments,               only: [:create]
  end
end

app/models/subscription_user.rb
class SubscriptionUser < ActiveRecord::Base
end

app/controllers/admin/subscription_users_controller.rb
module Admin
  class SubscriptionUsersController < Admin::BaseController
    helper_method :sort_column

    def index
      is_deleted = false
      is_deleted = true if params[:deleted] == 'true'
      @users = SubscriptionUser.where(:is_deleted => is_deleted).order(sort_column + " " + sort_direction).page(params[:page]).per(50)
      @users_count = SubscriptionUser.where(:is_deleted => is_deleted).count
    end

    def search
      @users = SubscriptionUser.where('email LIKE ?', '%' + params[:q] + '%').order(sort_column + " " + sort_direction).page(params[:page]).per(50)
      render :action => :index
    end

    def destroy
      user = SubscriptionUser.find(params[:id])
      if user.update_attribute(:is_deleted, true)
        flash[:notice] = "User successfully deleted"
      else
        flash[:error] = "Something went wrong while deleting user. Please try again later."
      end

      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end

    def restore
      user = SubscriptionUser.find(params[:id])
      if user.update_attribute(:is_deleted, false)
        flash[:notice] = "User successfully restored"
      else
        flash[:error] = "Something went wrong while restoring user. Please try again later."
      end

      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end

    private

    def sort_column
      super(SubscriptionUser, 'id')
    end
  end
end

app/helpers/admin/subscription_user_helper.rb
module Admin
  module SubscriptionUserHelper
    def last_signed_in_mobile_at(last_sign_in_at)
      return 'n/a' unless last_sign_in_at
      time_ago_in_words(last_sign_in_at) + ' ago'
    end

    def sign_up_time(date_time)
      return time_ago_in_words(date_time) + " ago" if date_time > 24.hours.ago
      date_time.to_s(:us)
    end
  end
end

app/views/admin/subscription_users/index.html.haml
%h3
  = "(" + @users_count.to_s + ")"
  - if params[:deleted] == 'true'
    Deleted
  - else
    Active
  Subscription Application Users

.search-box
  = form_tag search_admin_subscription_users_path, :method => 'get' do
    %p
      = text_field_tag :q, params[:q], :placeholder => 'search with email'
      = submit_tag 'Search', :name => nil
  = link_to("clear search parameters", admin_subscription_users_path)

= paginate(@users)
%table#users.table.table-hover.table-bordered
  %thead
    %tr
      %th
        ID
      %th
        Email
      %th
        = "Signed Up"
      %th
        Price Variable
      %th
        = sortable("last_sign_in_at", "Last signed in at")
      %th
        Completed Second Step
      %th
        Actions
  %tbody
    - for user in @users
      %tr
        %td
          = user.id
        %td
          = user.email
        %td
          = sign_up_time(user.created_at)
        %td
          = user.campaign
        %td
          = last_signed_in_mobile_at(user.last_sign_in_at)
        %td
          = yes_or_no(!user.upfront_cc_info_required?)
        %td
          .btn-group
            %a.btn.dropdown-toggle{'data-toggle' => "dropdown", :href => "#"}
              Actions
              %span.caret
            %ul.dropdown-menu
              %li
                - if user.is_deleted?
                  = link_to("Restore this User", restore_admin_subscription_user_path(user), :method => :post, :confirm => "Are you sure you want to restore this user with email #{user.email}?")
                - else
                  = link_to("Delete this User", admin_subscription_user_path(user), :method => :delete, :confirm => "Are you sure you want to delete this user with email #{user.email}?")