config/routes.rb
Interapptive::Application.routes.draw do

  root :to => 'admin::users#index', :constraints => lambda { |request| request.cookies['auth_token'] && request.cookies['is_admin'] }
  root :to => 'storybooks#index', :constraints => lambda { |request| request.cookies['auth_token'] }
  root :to => 'user_sessions#new'

  #get  'users/sign_up'  => 'users#new',             :as => 'sign_up'
  get  'users/sign_in'  => 'user_sessions#new',     :as => 'sign_in'
  post 'users/sign_in'  => 'user_sessions#create',  :as => ''
  match 'users/sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  get  'users/settings'  => 'users#edit'

  resource :user do
    collection { get :show_signed_in_as_user }
  end

  get  'password_reset'      => 'password_resets#new',   :as => :new_password_reset
  get  'password_resets/:id' => 'password_resets#edit',  :as => :edit_password_reset
  put  'password_resets/:id' => 'password_resets#update'
  post 'password_resets'     => 'password_resets#create'

  resource :compiler
  resource :confirmation, only: [:new, :create]
  resource :term,         only: [:new, :create], :path_names => { :new => 'accept' }, :path => 'terms'
  resource :kmetrics,   only: :create

  resources :images
  resources :videos
  resources :sounds
  resources :fonts

  get '/storybooks/main', to: redirect('/assets/init_storybook.js')
  get '/storybooks/res/:name', to: redirect('/assets/res/%{name}.png')
  resources :storybooks do
    resources :scenes do
      collection { put :sort }
    end

    resources :fonts
    resources :images
    resources :videos
    resources :sounds
    resources :assets, only: [:create, :index]

    resource :application_information, only: [:create, :update]
    resource :subscription_publish_information, only: [:update]
    resource :subscription_publish_request, only: [:create]

    get 'simulator/show' => 'simulator#show'
    get 'simulator/main', to: redirect('/assets/simulator.js')
  end

  resources :scenes do
    #resources :actions

    resources :keyframes do
      collection { put :sort }
    end
  end

  resources :keyframes

  resource :zencoder, :controller => :zencoder, :only => :create

  namespace :admin do
    root :to => 'users#index'

    resources :subscription_users do
      collection do
        get 'search'
      end

      member do
        post 'restore'
      end
    end

    resources :users do
      collection do
        get 'search'
      end
      member do
        post 'send_invitation'
        post 'restore'
      end
    end

    resource :subscription_publisher, only: :create

    resources :publish_requests,              only: [:index, :show, :update]
    resources :subscription_publish_requests, only: [:index, :show, :update]
    resources :storybook_assignments,         only: [:edit, :update]
    resources :storybook_archives,            only: [:create]
    resources :auto_alignments,               only: [:create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :password, :length => { :minimum => 6 }, 
            :on => :create

  validates :password, :length => { :minimum => 6 }, 
            :on => :update,
            :if => :password_digest_changed?

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email, :case_sensitive => false, :message => 'is in use.'
  validates_presence_of :email

  before_create { generate_token(:auth_token) }
  before_create { generate_token(:kissmetrics_identifier) }

  has_many :storybooks, :dependent => :destroy
  has_many :fonts, :through => :storybooks

  def backbone_response
    {
        'id'                       => id,
        'email'                    => email,
        'is_admin'                 => is_admin,
        'allowed_storybooks_count' => allowed_storybooks_count,
        'storybooks_count'         => storybooks.count,
        'created_at'               => created_at,
        'company'                  => company,
        'name'                     => name
    }
  end

  def confirm
    return true if confirmed?
    # It should be noted that validations are skipped with ActiveRecord::Base#update_attribute
    # because of which we do not get any errors on password of the user despite validations
    # in place.
    self.update_attribute(:confirmed, true)
  end

  def generate_token(column)
    self[column] = unique_token_for(column)
  end

  def unique_token_for(column)
    begin
      token = SecureRandom.urlsafe_base64
    end while User.exists?(column => token)
    token
  end

  def send_password_reset
    generate_token :password_reset_token
    self.password_reset_sent_at = Time.zone.now
    save!
    Resque.enqueue(MailerQueue, 'UserMailer', 'password_reset', self.id)
  end

  def reset_password
    pass = SecureRandom.base64(32).gsub(/[=+$\/]/, '').first(9)
    self.password = pass
    self.password_confirmation = pass
    if save
      Resque.enqueue(MailerQueue, 'UserMailer', 'password_reset_notification', self.id, pass)
      return true
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    def index
      is_deleted = false
      is_deleted = true if params[:deleted] == 'true'
      @users = User.where(:is_deleted => is_deleted).order('id DESC').page(params[:page]).per(50)
    end

    def search
      @users = User.where('email LIKE ?', '%' + params[:q] + '%').order('id DESC').page(params[:page]).per(50)
      render :action => :index
    end

    def edit
      @user = User.find(params[:id])
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      params[:user].slice!(:name, :city, :company, :email, :is_admin, :allowed_storybooks_count)

      if @user.update_attributes(params[:user])
        flash[:notice] = "User details were updated."
      else
        flash[:error] = "There was a problem updating user details. Please try again."
      end
      respond_to do |format|
        format.html { redirect_to :action => :edit }
      end
    end

    def new
      @user = User.new
    end

    def create
      params[:user].slice!(:name, :city, :company, :email, :is_admin, :allowed_storybooks_count)
      @user = User.new(params[:user])

      if @user.reset_password
        respond_to do |format|
          format.html { redirect_to edit_admin_user_url(@user.id) }
        end
      else
        respond_to do |format|
          format.html { render :action => :new }
        end
      end
    end

    def destroy
      user = User.find(params[:id])
      if user.update_attribute(:is_deleted, true)
        flash[:notice] = "User successfully deleted"
      else
        flash[:error] = "Something went wrong while deleting user. Please try again later."
      end

      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end

    def send_invitation
      @user = User.find(params[:id])
      if @user.reset_password
        respond_to do |format|
          format.js
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end

    def restore
      user = User.find(params[:id])
      if user.update_attribute(:is_deleted, false)
        flash[:notice] = "User successfully restored"
      else
        flash[:error] = "Something went wrong while restoring user. Please try again later."
      end

      respond_to do |format|
        format.html { redirect_to :action => :index }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]

  def show
    respond_to do |format|
      format.json { render :json => current_user.backbone_response }
    end
  end

  def show_signed_in_as_user
    respond_to do |format|
      format.json { render :json => signed_in_as_user.backbone_response }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html { render :layout => 'user_sessions' }
      format.json { render :json => @user }
    end
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      params[:user].slice!(:email, :password, :password_confirmation)

      if current_user.update_attributes params[:user]
        format.html { redirect_to current_user }
        format.json { head :ok }
      else
        format.html { render :action => :edit }
        format.json { render :json => current_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def create
    respond_to do |format|
      format.html { render :action => 'new', :layout => 'user_sessions' }
      format.json { render :json => {}, :status => :unprocessable_entity }
    end
  end

  def destroy
    current_user.destroy

    respond_to do |format|
      format.html { redirect_to sign_in_path }
      format.json { head :ok }
    end
  end
end

app/views/admin/users/edit.html.haml
%h1
  Editing User
#user.well
  #email
    Email:
    = @user.email
  %br

  = form_for @user, :url => admin_user_path(@user) do |f|
    %p
      = f.text_field :email, :placeholder => "Email"

    %p
      = f.number_field :allowed_storybooks_count, :placeholder => 'Allowed number of storybooks'
      %span Allowed Storybooks

    %p
      Is Admin?
      = f.check_box :is_admin

    = f.submit 'Update', :class => 'btn'

  = link_to('Users List', admin_users_path)

app/views/admin/users/index.html.haml
%h1 Users

.search-box
  = form_tag search_admin_users_path, :method => 'get' do
    %p
      = text_field_tag :q, params[:q], :placeholder => 'search with email'
      = submit_tag 'Search', :name => nil
  = link_to("clear search parameters", admin_users_path)

= paginate(@users)
%table#users.table.table-hover.table-bordered
  %thead
    %tr
      %th
        ID
      %th
        Email
      %th
        Name
      %th
        Signed Up
      %th
        Actions
  %tbody
    - for user in @users
      %tr
        %td
          = user.id
        %td
          = link_to(user.email, admin_user_path(user))
        %td
          = user.name
        %td
          = time_ago_in_words(user.created_at)
          ago
        %td
          .btn-group
            %a.btn.dropdown-toggle{'data-toggle' => "dropdown", :href => "#"}
              Actions
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to("Edit", edit_admin_user_path(user))
              %li
                - if user.is_deleted?
                  = link_to("Restore this User", restore_admin_user_path(user), :method => :post, :confirm => "Are you sure you want to restore this user with email #{user.email}?")
                - else
                  = link_to("Delete this User", admin_user_path(user), :method => :delete, :confirm => "Are you sure you want to delete this user with email #{user.email}?")
              %li
                = link_to("Resend Invite", send_invitation_admin_user_path(:id => user.id), :method => :post, :remote => true, :confirm => "This will change password of this user.")
              %li
                = link_to("Assign a Storybook", edit_admin_storybook_assignment_path(:id => user.id))
              %li
                = link_to("Sign In Like this User", storybooks_path(:signed_in_as_user_id => user.id))

app/views/admin/users/new.html.haml
%h1
  Creating User

= form_for @user, :url => admin_users_path, :html => { :class => 'well' } do |f|
  - if @user.errors.any?
    .errors
      %h2 There were problems with user data

      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  %p
    = f.text_field :name,     :placeholder => 'name'
  %p
    = f.text_field :company,  :placeholder => 'company'
  %p
    = f.text_field :city,     :placeholder => 'city'
  %p
    = f.text_field :email,    :placeholder => 'email'
  %p
    = f.number_field :allowed_storybooks_count, :placeholder => 'Allowed number of storybooks'
    %span Allowed Storybooks

  %p
    Is Admin?
    = f.check_box :is_admin

  %br/

  = f.submit 'Create', :class => 'btn'
  %br/

  = link_to('Users List', admin_users_path)

app/views/admin/users/send_invitation.js.haml
- if @user.valid?
  window.toastr['success']("Invitation email was sent successfully.")
- else
  window.toastr['error']("Something went wrong when sending invitation email.")

app/views/admin/users/show.html.haml
%h1 Showing User

#user.well
  %p
    %strong
      ID:
    = @user.id
  %p
    %strong
      Email:
    = @user.email
  %p
    %strong
      Is Admin: 
    = yes_or_no(@user.is_admin?)
  %p
    %strong
      Allowed Storybooks count: 
    = @user.allowed_storybooks_count
  %p
    %strong
      Stroybooks: 
    %ol
      - @user.storybooks.each do |storybook|
        %li
          = "(" + storybook.id.to_s +  ") " + storybook.title

  = link_to("Sign In Like this User", storybooks_path(:signed_in_as_user_id => @user.id))